# Generated by Django 3.0.6 on 2020-05-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('products_names', models.CharField(max_length=2000, verbose_name='Название продуктов')),
                ('calories', models.IntegerField(verbose_name='Калории')),
                ('protein', models.IntegerField(verbose_name='Белки')),
                ('carbohydrates', models.IntegerField(verbose_name='Углеводы')),
                ('fat', models.IntegerField(verbose_name='Жиры')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название')),
                ('calories', models.IntegerField(verbose_name='Калории')),
                ('protein', models.IntegerField(verbose_name='Белки')),
                ('carbohydrates', models.IntegerField(verbose_name='Углеводы')),
                ('fat', models.IntegerField(verbose_name='Жиры')),
            ],
        ),
    ]
